name: "HackerNews"

on:
  push:
     branches:
      - dev
      - main
  pull_request:
    paths:
      - '.swiftlint.yml'
      - ".github/workflows/**"
      - "HackerNews/**"
      - "HackerNewsTests/**"
      - "Modules/**"

jobs:
  iOS:
    name: 
    runs-on: macos-13
    strategy:
      fail-fast: false
      matrix:
        include:
          - destination: "OS=17.0,name=iPhone 14 Pro"
            name: "iOS"
            scheme: "Debug"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: make setup_build_tools
      - name: Generate resources
        run: make swiftgen
      - name: Generate project
        run: xcodegen generate
      - name: Select Xcode version
        run: sudo xcode-select -s '/Applications/Xcode_15.2.app/Contents/Developer'
      - name: Run tests
        run: |
          xcodebuild clean test \
            -scheme ${{ matrix.scheme }} \
            -destination "${{ matrix.destination }}" \
            -enableCodeCoverage YES || exit 1

  discover-typos:
    name: Discover Typos
    runs-on: macOS-12
    env:
      DEVELOPER_DIR: /Applications/Xcode_14.1.app/Contents/Developer
    steps:
      - uses: actions/checkout@v4
      - name: Discover typos
        run: |
          export PATH="$PATH:/Library/Frameworks/Python.framework/Versions/3.11/bin"
          python3 -m pip install --upgrade pip
          python3 -m pip install codespell
          codespell --ignore-words-list="hart,inout,msdos,sur" --skip="./.build/*,./.git/*,./fastlane/*"
